"""empty message

Revision ID: 56af51d19d88
Revises: ce85a010af11
Create Date: 2022-06-03 21:53:15.761181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56af51d19d88'
down_revision = 'ce85a010af11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
