"""empty message

Revision ID: 9bbc1564a63a
Revises: 38d084d925ce
Create Date: 2022-06-04 11:22:46.231949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbc1564a63a'
down_revision = '38d084d925ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genre', sa.ARRAY(sa.String()), server_default='{}', nullable=True))
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'genre')
    # ### end Alembic commands ###
